### ISSUE TITLE
Standardise Processor Packages

### ISSUE THREAD

**Issue by jamesdbaker** [annot8/annot8-components-deprecated#1]
At the moment, we split the `processors` package into a number of different sub-packages, with some sub-packages separated out by purpose and some by technique. We probably want to standardise on an approach for naming these to make things clear.

**Comment by jamesdbaker** [comment]
I've been thinking about how best to tackle this.

I don't think grouping by technique is a good idea, as at the end of the day users are more interested in what's being extracted rather than how. So we could group by themes (e.g. `processors.cyber` for things like e-mail addresses), but then how do we decide on those themes? And how do processors that don't work on annotations fit in (e.g. ones that create new items, or output results)?

Alternatively, we could put them all in one package with sensible names (perhaps grouped by some very high level concepts) and rely on a UI to make it easier for users to navigate the available processors.

Of course, the intention is that it's easy to include processors from external sources - so perhaps we don't want them in separate packages, but in separate modules/JARs (one repo) that can be built and included as required (alongside third party ones)? So a module for cyber 'entities', a module for working with text files, a module for outputting to the console? That reduces the footprint of Annot8 when deploying (particularly embedded) as you can be very explicit about what you do and don't want (e.g. if I'm using it to extract e-mail addresses and that's all I care about, I don't really want a whole load of OpenNLP models and classes bundled).

**Comment by stuarthendren** [comment]
I like the idea of separating by theme and I suspect there would be some base module with common support classes that are used in multiple themes. I think this would make it easy for a developer to select the dependencies they need. 

I think the theme themselves should be self selecting. Create what you need, if someone wants a theme that doesn't exist then they can create it. Themes could also come with some support for a particular type system.

I also think that the developer/user perspective is different and probably shouldn't be solved by the same answer. Initially I see this as a developers library and multiple UI based tools could be build using it. How they expose processors to their users, if at all, is the concern of that particular application.

**Comment by chrisflatley** [comment]
I think (and might be wrong on this) that the Java 9 module system doesn't work (well?) when different JARs having the same package in. I think Steve saw this on another project.

if I'm right, then you couldn't have a JAR (have an annot8.processors.cyber.Email processor) and another JAR with (have an annot8.processors.cyber.IP processor) and expect them to be merged. That does make things more complex.

Perhaps the solution (to offering nice user and developer experience) is that you can have some form a alias config file, which acts a look up between a friendly name and a class implementation:

```
alais:
   cyber-ip: io.annot8.components.processors.IP 
   cyber-email: com.example.annot8.processors.email.Email 
```

**Comment by jamesdbaker** [comment]
I didn't necessarily see it as a JAR per component, but rather all cyber components in one JAR. So for example, there might be a basic set of cyber processors that are developed as part of the Annot8 project in `io.annot8.components.cyber.*`, and then if I came along and developed my own I'd expect that to be in a separate package (e.g. `jamesbaker.annot8.components.cyber.*`). Would that work?

I think Stuart is right though, the user and the developer perspectives are probably different but that is the problem of something else rather than Annot8. Though we should still try and make life easy for developers with a sensible naming/packaging scheme!

**Comment by chrisflatley** [comment]
Yes, think that works personally.

(I guess the very off topic point I was thinking about was that it should be as easy to use  jamesbaker.annot8.components.cyber.* as it is io.annot8.components.cyber.*  - unlike in Baleen where the latter is a special case)

**Comment by jamesdbaker** [comment]
Absolutely, and I think that was one of the things we talked about when initially planning Annot8.

When I get a chance, I'll have a go at splitting out the existing components into separate packages (as an example if nothing else).
